include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    import_of_legacy_library_into_null_safe: ignore

  enable-experiment:
    - non-nullable
  plugins:
    - dart_code_metrics
  exclude:
    [build/**, ios/**, android/** ,lib/shared_preferences.dart, /.dart_tool, lib/core/ui/widgets/flutter_native/**, test/**/*.mocks.dart, lib/core/ui/assets/icon/itra_app_icons_icons.dart]

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - no-magic-number:
        severity: error
    - avoid-unused-parameters:
        severity: error
    - binary-expression-operand-order:
        severity: error
    - double-literal-format:
        severity: error
    - no-empty-block:
        severity: error
    - no-equal-then-else:
        severity: error
    - no-object-declaration:
        severity: error
    - prefer-conditional-expressions:
        severity: error
    - member-ordering:
        severity: error
        order:
          - public-fields
          - private-fields
          - constructors