name: after_approve_action

on:
  workflow_run:
    workflows: [Add Review Label]
    types:
      - completed

jobs:
  lint:
    timeout-minutes: 10
    needs: branchNamingRules
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Checkout SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_MODELS }}
      - name: Get packages in a Flutter project
        run: flutter pub get
      - name: Run lint
        run: dart analyze

  runTests:
    timeout-minutes: 30
    needs: lint
    name: Run tests and get coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_MODELS }}
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - name: Run tests
        run: flutter test

  buildServer:
    timeout-minutes: 10
    needs: runTests
    name: check build Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_MODELS }}
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: dart pub get
      - run: flutter build web

  addLabelReadyForMerge:
    timeout-minutes: 3
    needs: buildServer
    if: >-
      github.event.pull_request.user.login != 'octobot' &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: "add label 'ready for merge'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit $PR --add-label 'awaiting review'
