name: CI build

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - "main"

jobs:
  job1:
    uses: vkovalyov/checkCI/.github/workflows/notify.yml@v1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}