name: PR naming rules

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - "main"

jobs:
  pr-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: 'ITRAPP-\d+'
          max_length: 50
      - uses: vkovalyov/checkCI/.github/workflows/workflow.yml@main
       #my-org/some-repo/.github/workflows/build.yml@main