name: Verify PR

on:

  pull_request:
    types: [ opened, edited,synchronize ,reopened ]
    branches: [ main ]

jobs:
  cancel-previous-workflow-this-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  pr-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: 'ITRAPP-\d+'
          disallowed_prefixes: '[IN-PROGRESS]'
          max_length: 50

  branch-naming-rules:
    needs: pr-naming-rules
    name: branch naming
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: 'ITRAPP-\d+'
          ignore: master
          max_length: 50

  lint:
    needs: branch-naming-rules
    name: code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      - name: Get packages in a Flutter project
        run: flutter pub get
      - name: Run lint
        run: dart analyze


  run-tests:
    needs: lint
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - name: Run tests
        run: |
          flutter test --coverage --no-sound-null-safety;
      - name: Upload reports to codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}

  add-need-approve:
    needs: run-tests
    if: >-
      github.event.pull_request.user.login != 'octobot' &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: "add label 'awaiting review'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit $PR --add-label 'need approve'
          gh pr comment $PR --body '@vkovalyov  What do you think about these updates?'

  build-server:
    needs: run-tests
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: dart pub get
      - run: build dart compile exe bin/itrapp_backend.dart -o itrapp_backend --low-resources-mode